In [27]:
def func():
    try:
        print(5/0)
    except ZeroDivisionError:
        print("Cannot perform division, because entered expression is of the undeterminate form.")

func()

Cannot perform division, because entered expression is of the undeterminate form.


In [31]:
for subjct in ["Americans", "Indians"]:
    for verb in ["play", "watch"]:
        for obj in ["Baseball","Cricket"]:
            print(subjct,verb,obj)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [43]:
import numpy as np
def vandermonde(matrix,N):
    output = [[ele**i for i in range(N)] for ele in matrix]
    return np.array(output)

input_matrix = [3,4,5,8,6]
count = len(input_matrix)
print(vandermonde(input_matrix,count))

[[   1    3    9   27   81]
 [   1    4   16   64  256]
 [   1    5   25  125  625]
 [   1    8   64  512 4096]
 [   1    6   36  216 1296]]
